Repository TAIsRich/chuwa1010, pull requests merged in 2022-10, with the labels that each got.

#5 HW1
  Coding/codes
  ShortQuestions/hw1.md
Labels: bug

#25 Di lin/hw1
  ShortQuestions/hw1.md
  java-core/pom.xml
Labels: bug

#56 Libo cui/hw2
  Coding/ParkingLot/Motorcycle.java
  ShortQuestions/hw2.md
Labels: enhancement, conflicts

#89 Libo cui/hw4
  Coding/Main21.java
  Coding/Main212.java
  Coding/Main213.java
  stream-api-exercises-main/.gitignore
  stream-api-exercises-main/README.MD
  stream-api-exercises-main/blob/Data_Model.jpg
  stream-api-exercises-main/pom.xml
  stream-api-exercises-main/src/main/java/space/gavinklfong/demo/streamapi/AppCommandRunner.java
  stream-api-exercises-main/src/main/java/space/gavinklfong/demo/streamapi/DemoApplication.java
  stream-api-exercises-main/src/main/java/space/gavinklfong/demo/streamapi/models/Customer.java
  stream-api-exercises-main/src/main/java/space/gavinklfong/demo/streamapi/models/Order.java
  stream-api-exercises-main/src/main/java/space/gavinklfong/demo/streamapi/models/Product.java
  stream-api-exercises-main/src/main/java/space/gavinklfong/demo/streamapi/repos/CustomerRepo.java
  stream-api-exercises-main/src/main/java/space/gavinklfong/demo/streamapi/repos/OrderRepo.java
  stream-api-exercises-main/src/main/java/space/gavinklfong/demo/streamapi/repos/ProductRepo.java
  stream-api-exercises-main/src/main/resources/application.properties
  stream-api-exercises-main/src/main/resources/data.sql
  stream-api-exercises-main/src/main/resources/table_script.ddl
  stream-api-exercises-main/src/site/site.xml
  stream-api-exercises-main/src/test/java/space/gavinklfong/demo/streamapi/MyStreamApiTest.java
  stream-api-exercises-main/src/test/java/space/gavinklfong/demo/streamapi/StreamApiTest.java
  stream-api-exercises-main/src/test/resources/application.properties
Labels: conflicts

#79 hw3
  Coding/ParkingLot/Motorcycle.java
  MavenProject/pom.xml
  ShortQuestions/hw2.md
Labels: conflicts
